### ISSUE TITLE
AttributeError: 'module' object has no attribute 'generate_dendogram'

### ISSUE THREAD

**Issue by JingWangPanda** [taynaud/python-louvain#6]
(en1) wifiroam076032:python-louvain-master wangjing$ community karate.bin
Traceback (most recent call last):
  File "/Users/wangjing/virtualenv_files/en1/bin/community", line 4, in <module>
    __import__('pkg_resources').run_script('python-louvain==0.4', 'community')
  File "/Users/wangjing/virtualenv_files/en1/lib/python2.7/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/wangjing/virtualenv_files/en1/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1506, in run_script
    exec(script_code, namespace, namespace)
  File "/Users/wangjing/virtualenv_files/en1/lib/python2.7/site-packages/python_louvain-0.4-py2.7.egg/EGG-INFO/scripts/community", line 5, in <module>
    
AttributeError: 'module' object has no attribute 'generate_dendogram'

How can I solve this problem? please.

**Comment by taynaud** [comment]
Hi,

There was several issues in last release:

- I remove generate_dendogram to generate_dendrogram
- I rename load_binary to __load_binary

And since community was not using the python of current env but system one, I do not see it.

It is fixed in last commit, but I will only release it after networkx 2.0 release.


I think you can use python-louvain<0.4 which will not have the issue with the community script. But this script is not really usefull, the cpp implementation is a lot faster with its own binary format. If you use this package as a library, it is should be working.

**Comment by taynaud** [comment]
Networkx 2.0 release does not seem so imminent, I have make a 0.6 release fixing your issue
